using Microsoft.CodeAnalysis;
using Modulus.Generators.Tests.Helpers;
using Shouldly;
using Xunit;

namespace Modulus.Generators.Tests;

public class StronglyTypedIdGeneratorTests
{
    [Fact]
    public void Generate_GuidBackedId_ProducesAllExpectedCode()
    {
        var source = """
            using Modulus.Mediator.Abstractions;

            namespace TestNamespace;

            [StronglyTypedId]
            public readonly partial record struct OrderId;
            """;

        var (outputCompilation, diagnostics, runResult) = GeneratorTestHelper.RunGenerator(source);

        diagnostics.ShouldBeEmpty();
        runResult.GeneratedTrees.Length.ShouldBe(1);

        var generated = GeneratorTestHelper.GetGeneratedSource(runResult, "OrderId.g.cs");

        // Header
        generated.ShouldContain("// <auto-generated/>");
        generated.ShouldContain("#nullable enable");

        // Namespace
        generated.ShouldContain("namespace TestNamespace;");

        // Struct members
        generated.ShouldContain("public System.Guid Value { get; }");
        generated.ShouldContain("public OrderId(System.Guid value) => Value = value;");
        generated.ShouldContain("public static OrderId New() => new(System.Guid.NewGuid());");
        generated.ShouldContain("public static OrderId Empty => new(System.Guid.Empty);");
        generated.ShouldContain("public override string ToString() => Value.ToString();");

        // Attributes on struct
        generated.ShouldContain("[System.ComponentModel.TypeConverter(typeof(OrderId.OrderIdTypeConverter))]");
        generated.ShouldContain("[System.Text.Json.Serialization.JsonConverter(typeof(OrderId.OrderIdJsonConverter))]");

        // ValueConverter (nested inside the struct)
        generated.ShouldContain("public sealed class OrderIdValueConverter : Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<OrderId, System.Guid>");
        generated.ShouldContain("base(id => id.Value, value => new OrderId(value))");

        // JsonConverter (nested inside the struct)
        generated.ShouldContain("public sealed class OrderIdJsonConverter : System.Text.Json.Serialization.JsonConverter<OrderId>");
        generated.ShouldContain("reader.GetGuid()");
        generated.ShouldContain("writer.WriteStringValue(value.Value)");

        // TypeConverter (nested inside the struct)
        generated.ShouldContain("public sealed class OrderIdTypeConverter : System.ComponentModel.TypeConverter");
        generated.ShouldContain("System.Guid.Parse(s)");

        // Verify compilation has no errors
        var errors = outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();
        errors.ShouldBeEmpty();
    }

    [Fact]
    public void Generate_IntBackedId_ProducesCorrectConverters()
    {
        var source = """
            using Modulus.Mediator.Abstractions;

            namespace TestNamespace;

            [StronglyTypedId(typeof(int))]
            public readonly partial record struct ProductId;
            """;

        var (outputCompilation, diagnostics, runResult) = GeneratorTestHelper.RunGenerator(source);

        diagnostics.ShouldBeEmpty();
        runResult.GeneratedTrees.Length.ShouldBe(1);

        var generated = GeneratorTestHelper.GetGeneratedSource(runResult, "ProductId.g.cs");

        // Struct members — int backing
        generated.ShouldContain("public int Value { get; }");
        generated.ShouldContain("public ProductId(int value) => Value = value;");
        generated.ShouldNotContain("New()");
        generated.ShouldContain("public static ProductId Empty => new(0);");

        // ValueConverter
        generated.ShouldContain("ValueConverter<ProductId, int>");

        // JsonConverter
        generated.ShouldContain("reader.GetInt32()");
        generated.ShouldContain("writer.WriteNumberValue(value.Value)");

        // TypeConverter
        generated.ShouldContain("int.Parse(s)");

        // No compilation errors
        var errors = outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();
        errors.ShouldBeEmpty();
    }

    [Fact]
    public void Generate_LongBackedId_ProducesCorrectConverters()
    {
        var source = """
            using Modulus.Mediator.Abstractions;

            namespace TestNamespace;

            [StronglyTypedId(typeof(long))]
            public readonly partial record struct TransactionId;
            """;

        var (outputCompilation, diagnostics, runResult) = GeneratorTestHelper.RunGenerator(source);

        diagnostics.ShouldBeEmpty();
        runResult.GeneratedTrees.Length.ShouldBe(1);

        var generated = GeneratorTestHelper.GetGeneratedSource(runResult, "TransactionId.g.cs");

        // Struct members — long backing
        generated.ShouldContain("public long Value { get; }");
        generated.ShouldContain("public TransactionId(long value) => Value = value;");
        generated.ShouldNotContain("New()");
        generated.ShouldContain("public static TransactionId Empty => new(0L);");

        // ValueConverter
        generated.ShouldContain("ValueConverter<TransactionId, long>");

        // JsonConverter
        generated.ShouldContain("reader.GetInt64()");
        generated.ShouldContain("writer.WriteNumberValue(value.Value)");

        // TypeConverter
        generated.ShouldContain("long.Parse(s)");

        // No compilation errors
        var errors = outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();
        errors.ShouldBeEmpty();
    }

    [Fact]
    public void Generate_MultipleIds_EachGetsOwnGeneratedCode()
    {
        var source = """
            using Modulus.Mediator.Abstractions;

            namespace TestNamespace;

            [StronglyTypedId]
            public readonly partial record struct OrderId;

            [StronglyTypedId(typeof(int))]
            public readonly partial record struct LineItemId;
            """;

        var (outputCompilation, diagnostics, runResult) = GeneratorTestHelper.RunGenerator(source);

        diagnostics.ShouldBeEmpty();
        runResult.GeneratedTrees.Length.ShouldBe(2);

        var orderIdSource = GeneratorTestHelper.GetGeneratedSource(runResult, "OrderId.g.cs");
        var lineItemIdSource = GeneratorTestHelper.GetGeneratedSource(runResult, "LineItemId.g.cs");

        orderIdSource.ShouldContain("public System.Guid Value { get; }");
        orderIdSource.ShouldContain("OrderIdValueConverter");
        orderIdSource.ShouldContain("OrderIdJsonConverter");
        orderIdSource.ShouldContain("OrderIdTypeConverter");

        lineItemIdSource.ShouldContain("public int Value { get; }");
        lineItemIdSource.ShouldContain("LineItemIdValueConverter");
        lineItemIdSource.ShouldContain("LineItemIdJsonConverter");
        lineItemIdSource.ShouldContain("LineItemIdTypeConverter");

        // No compilation errors
        var errors = outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();
        errors.ShouldBeEmpty();
    }

    [Fact]
    public void Generate_NonPartialStruct_ReportsDiagnosticError()
    {
        var source = """
            using Modulus.Mediator.Abstractions;

            namespace TestNamespace;

            [StronglyTypedId]
            public readonly record struct OrderId;
            """;

        var (_, diagnostics, runResult) = GeneratorTestHelper.RunGenerator(source);

        runResult.GeneratedTrees.Length.ShouldBe(0);

        var generatorDiagnostics = runResult.Results
            .SelectMany(r => r.Diagnostics)
            .ToList();

        generatorDiagnostics.Count.ShouldBe(1);
        generatorDiagnostics[0].Id.ShouldBe("MODGEN001");
        generatorDiagnostics[0].Severity.ShouldBe(DiagnosticSeverity.Error);
        generatorDiagnostics[0].GetMessage().ShouldContain("OrderId");
        generatorDiagnostics[0].GetMessage().ShouldContain("partial");
    }

    [Fact]
    public void Generate_NonRecordStruct_ReportsDiagnosticError()
    {
        var source = """
            using Modulus.Mediator.Abstractions;

            namespace TestNamespace;

            [StronglyTypedId]
            public readonly partial struct OrderId;
            """;

        var (_, diagnostics, runResult) = GeneratorTestHelper.RunGenerator(source);

        runResult.GeneratedTrees.Length.ShouldBe(0);

        var generatorDiagnostics = runResult.Results
            .SelectMany(r => r.Diagnostics)
            .ToList();

        generatorDiagnostics.Count.ShouldBe(1);
        generatorDiagnostics[0].Id.ShouldBe("MODGEN002");
        generatorDiagnostics[0].Severity.ShouldBe(DiagnosticSeverity.Error);
        generatorDiagnostics[0].GetMessage().ShouldContain("OrderId");
        generatorDiagnostics[0].GetMessage().ShouldContain("record struct");
    }

    [Fact]
    public void Generate_GuidBackedId_ValueConverterRoundTrips()
    {
        var source = """
            using Modulus.Mediator.Abstractions;

            namespace TestNamespace;

            [StronglyTypedId]
            public readonly partial record struct OrderId;
            """;

        var (outputCompilation, _, runResult) = GeneratorTestHelper.RunGenerator(source);

        var generated = GeneratorTestHelper.GetGeneratedSource(runResult, "OrderId.g.cs");

        // Verify the ValueConverter contains correct round-trip logic
        generated.ShouldContain("base(id => id.Value, value => new OrderId(value))");

        // Verify no compilation errors — proves the converter is structurally valid
        var errors = outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();
        errors.ShouldBeEmpty();
    }

    [Fact]
    public void Generate_GuidBackedId_JsonConverterSerializesCorrectly()
    {
        var source = """
            using Modulus.Mediator.Abstractions;

            namespace TestNamespace;

            [StronglyTypedId]
            public readonly partial record struct OrderId;
            """;

        var (outputCompilation, _, runResult) = GeneratorTestHelper.RunGenerator(source);

        var generated = GeneratorTestHelper.GetGeneratedSource(runResult, "OrderId.g.cs");

        // Verify JsonConverter read/write methods
        generated.ShouldContain("reader.GetGuid()");
        generated.ShouldContain("writer.WriteStringValue(value.Value)");

        // Verify it inherits from the correct base class
        generated.ShouldContain("System.Text.Json.Serialization.JsonConverter<OrderId>");

        // Verify no compilation errors
        var errors = outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();
        errors.ShouldBeEmpty();
    }

    [Fact]
    public void Generate_GuidBackedId_TypeConverterParsesFromString()
    {
        var source = """
            using Modulus.Mediator.Abstractions;

            namespace TestNamespace;

            [StronglyTypedId]
            public readonly partial record struct OrderId;
            """;

        var (outputCompilation, _, runResult) = GeneratorTestHelper.RunGenerator(source);

        var generated = GeneratorTestHelper.GetGeneratedSource(runResult, "OrderId.g.cs");

        // Verify TypeConverter logic
        generated.ShouldContain("sourceType == typeof(string)");
        generated.ShouldContain("value is string s ? new OrderId(System.Guid.Parse(s))");

        // Verify it inherits from the correct base class
        generated.ShouldContain("System.ComponentModel.TypeConverter");

        // Verify no compilation errors
        var errors = outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();
        errors.ShouldBeEmpty();
    }
}
