using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Modulus.Generators;

[Generator]
public sealed class StronglyTypedIdGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Modulus.Mediator.Abstractions.StronglyTypedIdAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, static (spc, model) => Execute(spc, model!.Value));
    }

    private static StronglyTypedIdResult? GetModel(GeneratorAttributeSyntaxContext context)
    {
        var structDeclaration = (TypeDeclarationSyntax)context.TargetNode;
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var location = structDeclaration.Identifier.GetLocation();

        // Validate: must be partial (check first — more actionable)
        var isPartial = structDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword);
        if (!isPartial)
        {
            return new StronglyTypedIdResult(
                null,
                DiagnosticDescriptors.NonPartialStruct,
                location,
                symbol.Name);
        }

        // Validate: must be a record struct
        if (!symbol.IsRecord)
        {
            return new StronglyTypedIdResult(
                null,
                DiagnosticDescriptors.NonRecordStruct,
                location,
                symbol.Name);
        }

        // Extract backing type from attribute constructor argument
        var backingType = BackingType.Guid;
        var attributeData = context.Attributes[0];
        if (attributeData.ConstructorArguments.Length > 0)
        {
            var arg = attributeData.ConstructorArguments[0];
            if (arg.Value is INamedTypeSymbol typeSymbol)
            {
                backingType = typeSymbol.SpecialType switch
                {
                    SpecialType.System_Int32 => BackingType.Int,
                    SpecialType.System_Int64 => BackingType.Long,
                    _ => BackingType.Guid
                };
            }
        }

        var namespaceName = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();

        return new StronglyTypedIdResult(
            new StronglyTypedIdModel(symbol.Name, namespaceName, backingType),
            null,
            null,
            null);
    }

    private static void Execute(SourceProductionContext context, StronglyTypedIdResult result)
    {
        if (result.Diagnostic is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                result.Diagnostic,
                result.DiagnosticLocation,
                result.DiagnosticArg));
            return;
        }

        if (result.Model is null)
            return;

        var model = result.Model.Value;
        var source = GenerateSource(model);
        context.AddSource($"{model.TypeName}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    internal static string GenerateSource(StronglyTypedIdModel model)
    {
        var typeName = model.TypeName;
        var backingTypeName = GetBackingTypeName(model.BackingType);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // Partial struct with attributes
        sb.AppendLine($"[System.ComponentModel.TypeConverter(typeof({typeName}.{typeName}TypeConverter))]");
        sb.AppendLine($"[System.Text.Json.Serialization.JsonConverter(typeof({typeName}.{typeName}JsonConverter))]");
        sb.AppendLine($"public readonly partial record struct {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public {backingTypeName} Value {{ get; }}");
        sb.AppendLine();
        sb.AppendLine($"    public {typeName}({backingTypeName} value) => Value = value;");
        sb.AppendLine();

        if (model.BackingType == BackingType.Guid)
        {
            sb.AppendLine($"    public static {typeName} New() => new(System.Guid.NewGuid());");
            sb.AppendLine();
            sb.AppendLine($"    public static {typeName} Empty => new(System.Guid.Empty);");
        }
        else if (model.BackingType == BackingType.Long)
        {
            sb.AppendLine($"    public static {typeName} Empty => new(0L);");
        }
        else
        {
            sb.AppendLine($"    public static {typeName} Empty => new(0);");
        }

        sb.AppendLine();
        sb.AppendLine("    public override string ToString() => Value.ToString();");
        sb.AppendLine();

        // ValueConverter (nested inside the partial struct to stay in the same namespace)
        sb.AppendLine($"    public sealed class {typeName}ValueConverter : Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{typeName}, {backingTypeName}>");
        sb.AppendLine("{");
        sb.AppendLine($"        public {typeName}ValueConverter()");
        sb.AppendLine($"            : base(id => id.Value, value => new {typeName}(value)) {{ }}");
        sb.AppendLine("    }");
        sb.AppendLine();

        // JsonConverter
        var (jsonRead, jsonWrite) = model.BackingType switch
        {
            BackingType.Int => ("reader.GetInt32()", "writer.WriteNumberValue(value.Value)"),
            BackingType.Long => ("reader.GetInt64()", "writer.WriteNumberValue(value.Value)"),
            _ => ("reader.GetGuid()", "writer.WriteStringValue(value.Value)")
        };

        sb.AppendLine($"    public sealed class {typeName}JsonConverter : System.Text.Json.Serialization.JsonConverter<{typeName}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public override {typeName} Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine($"            => new({jsonRead});");
        sb.AppendLine();
        sb.AppendLine($"        public override void Write(System.Text.Json.Utf8JsonWriter writer, {typeName} value, System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine($"            => {jsonWrite};");
        sb.AppendLine("    }");
        sb.AppendLine();

        // TypeConverter
        var parseExpr = model.BackingType switch
        {
            BackingType.Int => "int.Parse(s)",
            BackingType.Long => "long.Parse(s)",
            _ => "System.Guid.Parse(s)"
        };

        sb.AppendLine($"    public sealed class {typeName}TypeConverter : System.ComponentModel.TypeConverter");
        sb.AppendLine("    {");
        sb.AppendLine("        public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, System.Type sourceType)");
        sb.AppendLine("            => sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);");
        sb.AppendLine();
        sb.AppendLine("        public override object? ConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object value)");
        sb.AppendLine($"            => value is string s ? new {typeName}({parseExpr}) : base.ConvertFrom(context, culture, value);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetBackingTypeName(BackingType backingType)
    {
        return backingType switch
        {
            BackingType.Int => "int",
            BackingType.Long => "long",
            _ => "System.Guid"
        };
    }
}

internal enum BackingType
{
    Guid,
    Int,
    Long
}

internal readonly struct StronglyTypedIdModel : IEquatable<StronglyTypedIdModel>
{
    public string TypeName { get; }
    public string? Namespace { get; }
    public BackingType BackingType { get; }

    public StronglyTypedIdModel(string typeName, string? ns, BackingType backingType)
    {
        TypeName = typeName;
        Namespace = ns;
        BackingType = backingType;
    }

    public bool Equals(StronglyTypedIdModel other) =>
        TypeName == other.TypeName &&
        Namespace == other.Namespace &&
        BackingType == other.BackingType;

    public override bool Equals(object obj) =>
        obj is StronglyTypedIdModel other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = TypeName?.GetHashCode() ?? 0;
            hash = (hash * 397) ^ (Namespace?.GetHashCode() ?? 0);
            hash = (hash * 397) ^ (int)BackingType;
            return hash;
        }
    }
}

internal readonly struct StronglyTypedIdResult : IEquatable<StronglyTypedIdResult>
{
    public StronglyTypedIdModel? Model { get; }
    public DiagnosticDescriptor? Diagnostic { get; }
    public Location? DiagnosticLocation { get; }
    public string? DiagnosticArg { get; }

    public StronglyTypedIdResult(
        StronglyTypedIdModel? model,
        DiagnosticDescriptor? diagnostic,
        Location? diagnosticLocation,
        string? diagnosticArg)
    {
        Model = model;
        Diagnostic = diagnostic;
        DiagnosticLocation = diagnosticLocation;
        DiagnosticArg = diagnosticArg;
    }

    public bool Equals(StronglyTypedIdResult other) =>
        Equals(Model, other.Model) &&
        Equals(Diagnostic, other.Diagnostic) &&
        DiagnosticArg == other.DiagnosticArg;

    public override bool Equals(object obj) =>
        obj is StronglyTypedIdResult other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = Model?.GetHashCode() ?? 0;
            hash = (hash * 397) ^ (Diagnostic?.GetHashCode() ?? 0);
            hash = (hash * 397) ^ (DiagnosticArg?.GetHashCode() ?? 0);
            return hash;
        }
    }
}